.phony: build

DOCKER_TAG  := $(shell git describe --always --tags)
DOCKER_HASH := $(shell git describe --always)

build:
	docker build --build-arg=tag="$(DOCKER_TAG)-$(DOCKER_HASH)" -t "foo:$(DOCKER_TAG)-$(DOCKER_HASH)" . 
